Introduce UINT64_MAX_SQRT
ethereum/consensus-specs pull request #3608
Opened 2024-02-16 07:41 UTC by mkalinin

Replaces the magic number introduced in https://github.com/ethereum/consensus-specs/pull/3600 with the corresponding constant

2024-02-16 14:38 UTC, djrtwo approved these changes

2024-02-19 07:47 UTC, hwwhww approved these changes
lgtm! Thank you @mkalinin!

2024-02-19 07:47 UTC, merged

2024-04-15 02:18 UTC, 120296 requested changes
Seúz

2024-04-15 02:26 UTC, 120296 requested changes
Sigue así